# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#q
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://127.0.0.1:5000/folder/handle?filename=2018-2019学年度第二学期学生综合素质测评分（2017级）.xls

#测试api连接
POST  http://192.168.56.101:5000/nav/classes

### 
#测试学院
POST  http://localhost:5000/nav/collage
Content-Type: application/json

{
    "year":2018,
    "term":"第一学期"
}
###